"""add user_id to Scroller model and add relationship to User model

Revision ID: b3594563d527
Revises: ebc8e356da8b
Create Date: 2022-04-18 13:01:20.918125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3594563d527'
down_revision = 'ebc8e356da8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scroller', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scroller', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scroller', type_='foreignkey')
    op.drop_column('scroller', 'user_id')
    # ### end Alembic commands ###
