"""initial migration

Revision ID: e2e1eb188c83
Revises: 
Create Date: 2022-04-09 13:24:26.022398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e1eb188c83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customhaiku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_one', sa.String(length=255), nullable=True),
    sa.Column('line_two', sa.String(length=255), nullable=True),
    sa.Column('line_three', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defaulthaiku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('line_one', sa.String(length=255), nullable=True),
    sa.Column('line_two', sa.String(length=255), nullable=True),
    sa.Column('line_three', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('longmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scroller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('to_recipient_name', sa.String(length=80), nullable=True),
    sa.Column('from_sender_name', sa.String(length=80), nullable=True),
    sa.Column('customhaiku_id', sa.Integer(), nullable=True),
    sa.Column('defaulthaiku_id', sa.Integer(), nullable=True),
    sa.Column('longmessage_id', sa.Integer(), nullable=True),
    sa.Column('mood_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customhaiku_id'], ['customhaiku.id'], ),
    sa.ForeignKeyConstraint(['defaulthaiku_id'], ['defaulthaiku.id'], ),
    sa.ForeignKeyConstraint(['longmessage_id'], ['longmessage.id'], ),
    sa.ForeignKeyConstraint(['mood_id'], ['mood.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scroller')
    op.drop_table('mood')
    op.drop_table('longmessage')
    op.drop_table('defaulthaiku')
    op.drop_table('customhaiku')
    # ### end Alembic commands ###
